Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2022-10, with the labels that each got.

#112 Implementation of OIDC authentication flow
  Dockerfile
  README.md
  config.js
  package-lock.json
  package.json
  public/config.js
  src/api/acme-account/backend.ts
  src/api/acme-profile/backend.ts
  src/api/administrators/backend.ts
  src/api/auditLogs/backend.ts
  src/api/auth/backend.ts
  src/api/authority/backend.ts
  src/api/certificates/backend.ts
  src/api/clients/backend.ts
  src/api/compliance-profile/backend.ts
  src/api/connectors/backend.ts
  src/api/credential/backend.ts
  src/api/dashboard/backend.ts
  src/api/discovery/backend.ts
  src/api/entity/backend.ts
  src/api/groups/backend.ts
  src/api/index.ts
  src/api/location/backend.ts
  src/api/operations/backend.ts
  src/api/profiles/backend.ts
  src/components/Layout/Header/index.tsx
  src/ducks/auth.ts
  src/utils/FetchHttpService/FetchHttpService.ts
  src/utils/FetchHttpService/FetchHttpServiceImpl.ts
  src/utils/FetchHttpService/index.ts
  start-nginx.sh
Labels: enhancement

#116 Minor fixes of previous release
  .gitignore
  src/components/Attributes/AttributeEditor/index.tsx
  src/ducks/connectors.ts
  src/ducks/locations.ts
  src/pages/locations/list/index.tsx
  src/pages/ra-profiles/list/index.tsx
  src/utils/attributes.ts
Labels: bug

#120 Bugfixing of users and roles management
  src/api/roles/model.ts
  src/api/users/backend.ts
  src/components/Forms/UserForm/index.tsx
  src/components/RolePermissionsEdior/index.tsx
  src/ducks/auth.ts
  src/ducks/transform/roles.ts
  src/models/roles.ts
  src/pages/certificates/detail/index.tsx
  src/pages/locations/detail/index.tsx
  src/pages/roles/detail/index.tsx
  src/pages/users/list/index.tsx
Labels: bug

#121 Fix adding rule to compliance profile - selected rule in table should contain all information including attributes
  src/api/compliance-profile/backend.ts
  src/api/compliance-profile/mock.ts
  src/api/compliance-profile/model.ts
  src/components/Attributes/ComplianceRuleAttributeViewer/index.tsx
  src/components/CustomTable/index.tsx
  src/ducks/compliance-profiles-epics.ts
  src/ducks/compliance-profiles.ts
  src/ducks/transform/compliance-profiles.ts
  src/models/compliance-profiles.ts
  src/pages/certificates/detail/index.tsx
  src/pages/compliance-profiles/detail/index.tsx
Labels: bug

#123 Redesign and fix role permissions editor
  src/api/roles/backend.ts
  src/api/roles/mock.ts
  src/api/roles/model.ts
  src/components/Forms/RoleForm/index.tsx
  src/components/Forms/RolePermissionsForm/index.tsx
  src/components/Forms/RoleUsersForm/index.tsx
  src/components/RolePermissionsEdior/index.tsx
  src/components/RolePermissionsEdior/style.module.scss
  src/components/WidgetButtons/index.tsx
  src/ducks/roles-epics.ts
  src/ducks/roles.ts
  src/ducks/users-epics.ts
  src/pages/roles/detail/index.tsx
  src/pages/roles/index.tsx
  src/pages/roles/list/index.tsx
  src/pages/roles/permissions/index.tsx
  src/pages/roles/users/index.tsx
Labels: enhancement

#124 Fix API endpoints for ACME and Compliance Profile
  src/api/profiles/backend.ts
  src/ducks/ra-profiles.ts
Labels: bug

#125 Fix handling of 403 when application hangs
  src/ducks/acme-accounts-epics.ts
  src/ducks/acme-profiles-epics.ts
  src/ducks/audit-epics.ts
  src/ducks/authorities-epics.ts
  src/ducks/certificates-epic.ts
  src/ducks/compliance-profiles-epics.ts
  src/ducks/connectors-epic.ts
  src/ducks/credentials-epics.ts
  src/ducks/discoveries-epics.ts
  src/ducks/entities-epics.ts
  src/ducks/groups-epics.ts
  src/ducks/locations-epics.ts
  src/ducks/ra-profiles-epics.ts
  src/ducks/roles-epics.ts
  src/ducks/users-epics.ts
Labels: bug

#127 Update URL regular expression
  src/utils/validators.ts
Labels: bug

#128 Disable checkboxes of resource actions when all actions are allowed
  src/components/RolePermissionsEdior/index.tsx
  src/pages/roles/detail/index.tsx
Labels: enhancement

#129 Allow edit object permissions while all resources/all actions are checked
  src/components/RolePermissionsEdior/index.tsx
  src/pages/roles/detail/index.tsx
Labels: bug

#130 Fix selecting all checkbox of table to select items only on current page
  src/components/CustomTable/index.tsx
Labels: bug

#134 Edit location redirection fix
  src/pages/locations/detail/index.tsx
  src/pages/locations/index.tsx
Labels: bug, ignore-for-release

#136 Fix redirection issues on the FE for Compliance and RA Profile
  src/api/compliance-profile/backend.ts
  src/api/compliance-profile/mock.ts
  src/api/compliance-profile/model.ts
  src/api/entity/backend.ts
  src/api/profiles/backend.ts
  src/components/pages/compliance-profiles/AssociateRaProfileDialogBody.tsx
  src/ducks/certificates.ts
  src/ducks/entities-epics.ts
  src/ducks/locations-epics.ts
  src/mocks/db-compliance-profiles.ts
  src/models/compliance-profiles.ts
  src/pages/certificates/detail/index.tsx
  src/pages/certificates/list/index.tsx
  src/pages/compliance-profiles/detail/index.tsx
  src/pages/locations/detail/index.tsx
  src/pages/ra-profiles/detail/index.tsx
Labels: bug

#137 Fix attribute loading and display in edit entity form
  src/components/Forms/EntityForm/index.tsx
  src/ducks/entities-epics.ts
Labels: bug

#138 Edit of entity does not show attributes editor
  src/components/Forms/EntityForm/index.tsx
Labels: bug

#141 Release/2.4.0
  README.md
  package.json
Labels: ignore-for-release

#147 Fix audit log listing pagination
  src/utils/FetchHttpService/FetchHttpServiceImpl.ts
Labels: bug

#146 Refresh certificate history when actions on certificate are executed
  src/ducks/certificates-epic.ts
  src/ducks/index.ts
  src/ducks/locations-epics.ts
  src/ducks/locations.ts
  src/pages/certificates/detail/index.tsx
Labels: bug

#150 Removed duplicate call to request certificate groups
  src/pages/certificates/detail/index.tsx
Labels: bug

#151 Refresh of detail and list of connectors after its approval
  src/ducks/connectors-epic.ts
  src/ducks/connectors.ts
  src/pages/connectors/detail/index.tsx
  src/pages/connectors/list/index.tsx
Labels: bug

#152 Improve error displaying
  src/components/Alerts/index.tsx
  src/components/CustomTable/index.tsx
  src/components/Forms/CredentialForm/index.tsx
  src/ducks/alerts.ts
  src/pages/certificates/list/index.tsx
  src/utils/net.ts
Labels: enhancement
