Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-07, with the labels that each got.

#386 Fix multiple callbacks calls
  src/components/Attributes/AttributeEditor/index.tsx
Labels: bug

#387 Visualize related objects of certificate with ReactFlow
  package-lock.json
  package.json
  src/components/FlowChart/CustomEdge/FloatingConnectionLine.tsx
  src/components/FlowChart/CustomEdge/edgeUtils.ts
  src/components/FlowChart/CustomEdge/index.tsx
  src/components/FlowChart/CustomFlowNode/customFlowNode.module.scss
  src/components/FlowChart/CustomFlowNode/index.tsx
  src/components/FlowChart/flowChart.module.scss
  src/components/FlowChart/index.tsx
  src/components/_pages/certificates/detail/certificateDetail.module.scss
  src/components/_pages/certificates/detail/index.tsx
  src/ducks/transform/certificates.ts
  src/resources/styles/_mixins.scss
  src/types/flowchart.ts
  src/utils/common-hooks.ts
Labels: new-feature

#404 Fix certificate detail widget lock and refresh functionality
  package-lock.json
  src/components/FlowChart/CustomFlowNode/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/ducks/certificates-epics.ts
  src/types/widget-locks.ts
Labels: bug, ignore-for-release

#410 Add certificate request tab to certificate details page
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/_pages/certificates/Asn1Dialog/Asn1Dialog.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateRenewDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/ducks/transform/utilsCertificateRequest.ts
  src/ducks/utilsCertificateRequest-epics.ts
  src/ducks/utilsCertificateRequest.ts
  src/types/utilsCertificate.ts
Labels: enhancement

#415 Add management of approval profiles
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/Layout/TabLayout/index.tsx
  src/components/_pages/approval-profiles/detail/index.tsx
  src/components/_pages/approval-profiles/form/approval-step-field.tsx
  src/components/_pages/approval-profiles/form/approvalProfile.module.scss
  src/components/_pages/approval-profiles/form/index.tsx
  src/components/_pages/approval-profiles/list/index.tsx
  src/ducks/approval-profiles-epics.ts
  src/ducks/approval-profiles.ts
  src/ducks/filters.ts
  src/ducks/index.ts
  src/ducks/transform/approval-profiles.ts
  src/types/approval-profiles.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/ApprovalProfileInventoryApi.ts
  src/types/openapi/apis/index.ts
  src/types/openapi/models/ApprovalProfileDetailDto.ts
  src/types/openapi/models/ApprovalProfileDto.ts
  src/types/openapi/models/ApprovalProfileRequestDto.ts
  src/types/openapi/models/ApprovalProfileResponseDto.ts
  src/types/openapi/models/ApprovalProfileUpdateRequestDto.ts
  src/types/openapi/models/ApprovalStepDto.ts
  src/types/openapi/models/Resource.ts
  src/types/openapi/models/index.ts
  src/utils/validators.ts
Labels: new-feature
