Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-02, with the labels that each got.

#208 Fix audit logs export
  src/components/_pages/auditLogs/index.tsx
  src/ducks/auditLogs-epics.ts
  src/ducks/auditLogs.ts
Labels: bug

#210 Minor bugfixes
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/Attributes/ComplianceRuleAttributeViewer/index.tsx
  src/components/CustomTable/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/compliance-profiles/detail/index.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/group/form/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/ducks/acme-profiles-epics.ts
  src/ducks/authorities-epics.ts
  src/ducks/certificateGroups-epics.ts
  src/ducks/certificates-epics.ts
  src/ducks/compliance-profiles-epics.ts
  src/ducks/connectors-epic.ts
  src/ducks/credentials-epics.ts
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/customAttributes-epics.ts
  src/ducks/discoveries-epics.ts
  src/ducks/ra-profiles-epics.ts
  src/ducks/token-profiles-epics.ts
  src/ducks/tokens-epics.ts
  src/resources/styles/_overrides.scss
Labels: bug

#214 Redesign certificate issue and rekey form
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateRenewDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/ducks/connectors-epic.ts
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/cryptographic-keys.ts
  src/types/openapi/apis/CryptographicKeyControllerApi.ts
  src/types/openapi/models/MimeType.ts
  src/types/openapi/src/doc-openapi-czertainly-core.yaml
Labels: enhancement, ignore-for-release

#215 UI fixes on cryptographic Provider
  src/components/_pages/cryptographic-keys/form/index.tsx
  src/components/_pages/token-profiles/form/index.tsx
  src/ducks/cryptographic-keys.ts
Labels: bug, ignore-for-release

#217 Hide Key format when the token profile is not selected
  src/components/_pages/cryptographic-keys/form/index.tsx
Labels: enhancement, ignore-for-release

#221 Fix search number filter
  src/components/FilterWidget/index.tsx
Labels: bug

#223 Change position of custom attribute widget in ACME profile detail page
  src/components/_pages/acme-profiles/detail/index.tsx
Labels: enhancement

#222 Key Updates and bug fixes
  src/components/CustomTable/index.tsx
  src/components/WidgetButtons/index.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/cryptographic-keys/KeyFilter/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/SignVerifyData.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
  src/components/_pages/tokens/detail/RandomDataGeneration.tsx
  src/components/_pages/tokens/detail/index.tsx
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/cryptographic-keys.ts
  src/ducks/transform/cryptographic-keys.ts
  src/types/cryptographic-keys.ts
  src/types/openapi/apis/CryptographicKeyControllerApi.ts
  src/types/openapi/models/CryptographicKeyResponseDto.ts
  src/types/openapi/models/KeyCompromiseReason.ts
  src/types/openapi/models/KeyDto.ts
  src/types/openapi/models/KeyItemDetailDto.ts
  src/types/openapi/models/KeyItemDto.ts
  src/types/openapi/models/MimeType.ts
  src/types/openapi/models/TokenProfileDto.ts
  src/types/openapi/src/doc-openapi-czertainly-core.yaml
Labels: enhancement

#224 Key Usage Fixes for the key list and details page
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/token-profiles/detail/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
Labels: bug, ignore-for-release

#226 Split the DTOs for certificate list and detail page
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/CertificateAttributes/index.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
  src/components/_pages/users/form/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/ducks/transform/certificates.ts
  src/types/certificate.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/CertificateInventoryApi.ts
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateDto.ts
  src/types/openapi/models/KeyDto.ts
  src/types/openapi/models/index.ts
  src/types/openapi/src/doc-openapi-czertainly-core.yaml
  src/utils/certificate.ts
  src/utils/download.ts
Labels: enhancement

#227 Minor UI bugs and text changes
  src/components/AppRouter.tsx
  src/components/Layout/Footer/index.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/about/index.tsx
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
  src/components/_pages/connectors/detail/index.tsx
  src/components/_pages/home/index.tsx
  src/utils/validators.ts
Labels: bug

#228 Add endpoint for downloading of certificate form list page
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/ducks/transform/certificates.ts
  src/types/certificate.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/CertificateInventoryApi.ts
  src/types/openapi/models/CertificateContentDto.ts
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateDto.ts
  src/types/openapi/models/MimeType.ts
  src/types/openapi/models/index.ts
  src/types/openapi/src/doc-openapi-czertainly-core.yaml
  src/utils/download.ts
Labels: bug

#229 Update rekey of certificate based on RFC
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/types/openapi/models/ClientCertificateRekeyRequestDto.ts
  src/types/openapi/models/MimeType.ts
  src/types/openapi/src/doc-openapi-czertainly-core.yaml
Labels: enhancement, ignore-for-release

#230 Add label for cryptography provider function group
  src/utils/attributes/attributes.tsx
Labels: bug

#235 Integrate utils service and use it to parse uploaded certificates and CSRs
  openapitools.json
  package.json
  src/api.ts
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateRenewDialog/index.tsx
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/ducks/index.ts
  src/ducks/transform/utilsCertificate.ts
  src/ducks/transform/utilsCertificateRequest.ts
  src/ducks/utilsCertificate-epics.ts
  src/ducks/utilsCertificate.ts
  src/ducks/utilsCertificateRequest-epics.ts
  src/ducks/utilsCertificateRequest.ts
  src/ducks/utilsOid-epics.ts
  src/ducks/utilsOid.ts
  src/types/openapi/src/doc-openapi-czertainly-core.yaml
  src/types/openapi/utils/.gitignore
  src/types/openapi/utils/.openapi-generator-ignore
  src/types/openapi/utils/.openapi-generator/FILES
  src/types/openapi/utils/.openapi-generator/VERSION
  src/types/openapi/utils/apis/CertificateUtilsAPIApi.ts
  src/types/openapi/utils/apis/CertificationRequestUtilsAPIApi.ts
  src/types/openapi/utils/apis/OIDUtilsAPIApi.ts
  src/types/openapi/utils/apis/index.ts
  src/types/openapi/utils/index.ts
  src/types/openapi/utils/models/ApiErrorResponseDto.ts
  src/types/openapi/utils/models/CertificateData.ts
  src/types/openapi/utils/models/ErrorMessageDto.ts
  src/types/openapi/utils/models/IdentifyCertificateRequestDto.ts
  src/types/openapi/utils/models/IdentifyCertificateResponseDto.ts
  src/types/openapi/utils/models/OidInfoResponseDto.ts
  src/types/openapi/utils/models/ParseCertificateRequestDto.ts
  src/types/openapi/utils/models/ParseCertificateResponseDto.ts
  src/types/openapi/utils/models/ParseRequestRequestDto.ts
  src/types/openapi/utils/models/ParseRequestResponseDto.ts
  src/types/openapi/utils/models/Pkcs10RequestAsn1Data.ts
  src/types/openapi/utils/models/Pkcs10RequestBasicData.ts
  src/types/openapi/utils/models/Pkcs10RequestExtendedData.ts
  src/types/openapi/utils/models/RandomCertificateResponseDto.ts
  src/types/openapi/utils/models/RequestData.ts
  src/types/openapi/utils/models/X509CertificateAsn1Data.ts
  src/types/openapi/utils/models/X509CertificateBasicData.ts
  src/types/openapi/utils/models/X509CertificateExtendedData.ts
  src/types/openapi/utils/models/index.ts
  src/types/openapi/utils/runtime.ts
  src/types/openapi/utils/servers.ts
  src/types/openapi/utils/tsconfig.json
  src/types/utilsCertificate.ts
  src/types/utilsCertificateRequest.ts
  src/utils/certificate.ts
Labels: enhancement

#237 Update Dockerfile and variables
  Dockerfile
  package-lock.json
  package.json
  src/components/AppRouter.tsx
  yarn.lock
Labels: enhancement

#238 Fix URL redirecting in Access control pages and ACME profile
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/roles/list/index.tsx
  src/components/_pages/users/detail/index.tsx
Labels: bug, ignore-for-release

#242 Global metadata management
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Dialog/index.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/global-metadata/detail/index.tsx
  src/components/_pages/global-metadata/form/index.tsx
  src/components/_pages/global-metadata/list/ConnectorMetadataDialog.tsx
  src/components/_pages/global-metadata/list/index.tsx
  src/ducks/customAttributes.ts
  src/ducks/globalMetadata-epics.ts
  src/ducks/globalMetadata.ts
  src/ducks/index.ts
  src/ducks/transform/globalMetadata.ts
  src/types/globalMetadata.ts
Labels: new-feature
