Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-04, with the labels that each got.

#284 Management of SCEP profiles
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Input/TextField/index.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/ra-profiles/ProtocolActivationDialogBody.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/components/_pages/scep-profiles/detail/index.tsx
  src/components/_pages/scep-profiles/form/index.tsx
  src/components/_pages/scep-profiles/list/index.tsx
  src/ducks/index.ts
  src/ducks/ra-profiles-epics.ts
  src/ducks/ra-profiles.ts
  src/ducks/scep-profiles-epics.ts
  src/ducks/scep-profiles.ts
  src/ducks/transform/ra-profiles.ts
  src/ducks/transform/scep-profiles.ts
  src/types/openapi/apis/SCEPProfileManagementApi.ts
  src/types/openapi/models/ScepProfileDetailDto.ts
  src/types/openapi/models/ScepProfileEditRequestDto.ts
  src/types/openapi/models/ScepProfileRequestDto.ts
  src/types/ra-profiles.ts
  src/types/scep-profiles.ts
Labels: new-feature

#285 Fix redirect to RA profile detail URL from ACME and SCEP profile
  src/components/_pages/acme-profiles/detail/index.tsx
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/ra-profiles/ProtocolActivationDialogBody.tsx
  src/components/_pages/scep-profiles/detail/index.tsx
  src/components/_pages/scep-profiles/form/index.tsx
  src/components/_pages/tokens/TokenActivationDialogBody.tsx
  src/ducks/certificates-epics.ts
  src/ducks/ra-profiles-epics.ts
Labels: bug, ignore-for-release

#288 Debounce attribute callbacks requests
  package-lock.json
  package.json
  src/components/Attributes/AttributeEditor/index.tsx
  src/components/_pages/platform-settings/form/index.tsx
Labels: enhancement, ignore-for-release

#290 Add search filters to discoveries inventory with support for pagination
  src/components/_pages/discoveries/DiscoveriesFilter/index.tsx
  src/components/_pages/discoveries/list/index.tsx
  src/ducks/discoveries-epics.ts
  src/ducks/discoveries.ts
Labels: enhancement

#291 Add search filters to entities and locations inventory with support for pagination
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/entities/EntitiesFilter/index.tsx
  src/components/_pages/entities/list/index.tsx
  src/components/_pages/locations/LocationsFilter/index.tsx
  src/components/_pages/locations/form/index.tsx
  src/components/_pages/locations/list/index.tsx
  src/ducks/entities-epics.ts
  src/ducks/entities.ts
  src/ducks/locations-epics.ts
  src/ducks/locations.ts
Labels: enhancement

#295 Change FileAttributeContentData MimeType to string
  package.json
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/Attributes/AttributeEditor/index.tsx
  src/types/attributes.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/models/FileAttributeContentData.ts
  src/types/openapi/models/MimeType.ts
  src/types/openapi/models/index.ts
Labels: bug

#298 Refactor tables pagination and search filters
  src/components/FilterWidget/index.tsx
  src/components/PagedList/PagedList.tsx
  src/components/_pages/certificates/CertificateInventoryFilter/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/cryptographic-keys/KeyFilter/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/discoveries/DiscoveriesFilter/index.tsx
  src/components/_pages/discoveries/list/index.tsx
  src/components/_pages/entities/EntitiesFilter/index.tsx
  src/components/_pages/entities/list/index.tsx
  src/components/_pages/locations/LocationsFilter/index.tsx
  src/components/_pages/locations/form/index.tsx
  src/components/_pages/locations/list/index.tsx
  src/components/_pages/users/form/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/cryptographic-keys.ts
  src/ducks/discoveries-epics.ts
  src/ducks/discoveries.ts
  src/ducks/entities-epics.ts
  src/ducks/entities.ts
  src/ducks/filters-epics.ts
  src/ducks/filters.ts
  src/ducks/index.ts
  src/ducks/locations-epics.ts
  src/ducks/locations.ts
  src/ducks/paging.ts
Labels: ignore-for-release, refactoring

#303 Fix triggering multiple callbacks with debounce
  src/components/Attributes/AttributeEditor/index.tsx
Labels: bug
