Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-08, with the labels that each got.

#419 Handle CodeBlock attribute content data with missing code property
  src/components/Attributes/CodeBlock/index.tsx
  src/utils/attributes/attributes.tsx
Labels: bug, ignore-for-release

#421 Update APIs and models
  src/components/AppRouter.tsx
  src/components/_pages/approval-profiles/detail/index.tsx
  src/components/_pages/approval-profiles/form/index.tsx
  src/ducks/approval-profiles-epics.ts
  src/ducks/approval-profiles.ts
  src/ducks/transform/approval-profiles.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/ApprovalInventoryApi.ts
  src/types/openapi/apis/ApprovalProfileInventoryApi.ts
  src/types/openapi/apis/CertificateInventoryApi.ts
  src/types/openapi/apis/NotificationManagementApi.ts
  src/types/openapi/apis/RAProfileManagementApi.ts
  src/types/openapi/apis/SettingsApi.ts
  src/types/openapi/apis/index.ts
  src/types/openapi/models/ApprovalDetailDto.ts
  src/types/openapi/models/ApprovalDetailStepDto.ts
  src/types/openapi/models/ApprovalDto.ts
  src/types/openapi/models/ApprovalProfileForVersionDto.ts
  src/types/openapi/models/ApprovalResponseDto.ts
  src/types/openapi/models/ApprovalStepRecipientDto.ts
  src/types/openapi/models/ApprovalUserDto.ts
  src/types/openapi/models/AttributeMappingDto.ts
  src/types/openapi/models/AuditLogDto.ts
  src/types/openapi/models/AuditLogFilter.ts
  src/types/openapi/models/FunctionGroupCode.ts
  src/types/openapi/models/NotificationInstanceDto.ts
  src/types/openapi/models/NotificationInstanceRequestDto.ts
  src/types/openapi/models/NotificationInstanceUpdateRequestDto.ts
  src/types/openapi/models/NotificationSettingsDto.ts
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/Resource.ts
  src/types/openapi/models/RoleDetailDto.ts
  src/types/openapi/models/RoleDto.ts
  src/types/openapi/models/RoleRequestDto.ts
  src/types/openapi/models/UserApprovalDto.ts
  src/types/openapi/models/index.ts
Labels: enhancement, ignore-for-release

#424 Add approvals mananagement
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/StatusBadge/index.tsx
  src/components/WidgetButtons/index.tsx
  src/components/_pages/approval-profiles/detail/index.tsx
  src/components/_pages/approval-profiles/list/index.tsx
  src/components/_pages/approvals/details/index.tsx
  src/components/_pages/approvals/list/index.tsx
  src/ducks/approval-profiles.ts
  src/ducks/approvals-epic.ts
  src/ducks/approvals.ts
  src/ducks/index.ts
  src/ducks/transform/approvals.ts
  src/types/approvals.ts
  src/types/openapi/apis/ApprovalInventoryApi.ts
  src/types/openapi/apis/ApprovalProfileInventoryApi.ts
  src/types/openapi/apis/AuditLogApi.ts
  src/types/openapi/apis/CertificateInventoryApi.ts
  src/types/openapi/apis/NotificationsApi.ts
  src/types/openapi/apis/ScheduledJobsManagementApi.ts
  src/types/openapi/models/ApprovalDetailDto.ts
  src/types/openapi/models/ApprovalDto.ts
  src/types/openapi/models/ClientCertificateRequestDto.ts
  src/types/openapi/models/Resource.ts
  src/utils/resource.tsx
Labels: new-feature

#428 Add email to groups and roles
  src/components/_pages/group/detail/index.tsx
  src/components/_pages/group/form/index.tsx
  src/components/_pages/group/list/index.tsx
  src/components/_pages/roles/RoleForm/index.tsx
  src/components/_pages/roles/detail/index.tsx
  src/components/_pages/roles/list/index.tsx
Labels: enhancement

#425 Assigning approval profile to RA profiles
  src/components/_pages/ra-profiles/AssociateApprovalProfileDialogBody.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/ducks/approval-profiles-epics.ts
  src/ducks/approval-profiles.ts
  src/ducks/ra-profiles-epics.ts
  src/ducks/ra-profiles.ts
Labels: new-feature

#429 Changes in listing of approvals - pagination reset and hide unavailable actions
  src/components/AppRouter.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/WidgetButtons/index.tsx
  src/components/_pages/approvals/details/index.tsx
  src/components/_pages/approvals/list/index.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
Labels: bug, ignore-for-release

#430 Fix certificate tab history blocked and wrong certificate key redirect
  src/components/Layout/TabLayout/index.tsx
Labels: bug, ignore-for-release

#432 Add certificate approvals tab to certificate detail
  src/components/Layout/TabLayout/index.tsx
  src/components/_pages/approval-profiles/detail/index.tsx
  src/components/_pages/approval-profiles/form/approval-step-field.tsx
  src/components/_pages/approvals/details/index.tsx
  src/components/_pages/approvals/list/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/types/openapi/models/ApprovalProfileDetailDto.ts
  src/types/openapi/models/ApprovalProfileDto.ts
  src/utils/resource.tsx
Labels: enhancement

#431 Add notifications settings
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/notifications/notifications-setting/index.tsx
  src/ducks/notifications-epics.ts
  src/ducks/notifications.ts
  src/ducks/settings-epics.ts
  src/ducks/settings.ts
Labels: enhancement

#437 Add number of associations to approval profiles listing table
  src/components/_pages/approval-profiles/list/index.tsx
Labels: enhancement, ignore-for-release

#439 Fix revoke certificate reason enum used in revoke operation popup
  src/components/StatusBadge/index.tsx
  src/components/_pages/approval-profiles/detail/index.tsx
  src/components/_pages/approval-profiles/form/approval-step-field.tsx
  src/components/_pages/approval-profiles/form/index.tsx
  src/components/_pages/approvals/details/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/compliance-profiles/detail/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/notifications/notification-instance-details/index.tsx
  src/components/_pages/notifications/notification-instance-form/index.tsx
  src/components/_pages/notifications/notifications-instances/index.tsx
  src/components/_pages/notifications/notifications-setting/index.tsx
  src/components/_pages/ra-profiles/AssociateApprovalProfileDialogBody.tsx
  src/components/_pages/roles/RoleForm/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/notifications-epics.ts
Labels: bug

#440 Fix SonarQube issues
  src/components/StatusBadge/index.tsx
  src/components/_pages/scheduler/detail/index.tsx
  src/components/_pages/users/form/index.tsx
  src/ducks/cryptographic-keys.ts
  src/utils/attributes/attributes.tsx
Labels: bug, ignore-for-release

#441 Remove spinner on notification icon when fetching new notifications
  src/components/_pages/notifications/overview/index.tsx
  src/ducks/notifications.ts
  src/utils/attributes/attributes.tsx
Labels: enhancement, ignore-for-release

#457 Add support for legacy authority provider
  src/components/_pages/authorities/form/index.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/ducks/authorities-epics.ts
  src/ducks/authorities.ts
  src/ducks/certificates-epics.ts
  src/ducks/transform/ra-profiles.ts
  src/types/openapi/models/CertificateEventHistoryDto.ts
  src/types/openapi/models/CertificateInLocationDto.ts
  src/types/openapi/models/RaProfileDto.ts
Labels: enhancement, ignore-for-release

#461 Download certificate request in PEM and DER format
  src/components/_pages/certificates/detail/index.tsx
Labels: enhancement
