Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-01, with the labels that each got.

#173 Update attribute descriptor viewer
  src/components/Attributes/AttributeDescriptorViewer/index.tsx
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/_pages/certificates/CertificateInventoryFilter/index.tsx
  src/ducks/connectors-epic.ts
Labels: enhancement, ignore-for-release

#176 add group attributes to all forms
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/authorities/form/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/compliance-profiles/form/AddRuleWithAttributesDialogBody/index..tsx
  src/components/_pages/credentials/form/index.tsx
  src/components/_pages/entities/form/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/locations/form/index.tsx
  src/components/_pages/ra-profiles/AcmeProtocolActivationDialogBody.tsx
  src/components/_pages/ra-profiles/form/index.tsx
Labels: enhancement, ignore-for-release

#178 Update metadata viewer to display attribute based metadata
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/CustomTable/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/credentials/form/index.tsx
  src/components/_pages/discoveries/detail/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/types/locations.ts
Labels: enhancement

#180 Fix attribute form checkbox initial value
  src/components/Attributes/AttributeEditor/index.tsx
Labels: bug

#181 add link to detail of discovered certificate
  src/components/_pages/discoveries/detail/index.tsx
  src/types/attributes.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/AuditLogApi.ts
  src/types/openapi/models/AttributeContentType.ts
  src/types/openapi/models/AttributeType.ts
  src/types/openapi/models/CredentialAttributeContent.ts
  src/types/openapi/models/CredentialAttributeContentData.ts
  src/types/openapi/models/CredentialDto.ts
  src/types/openapi/models/DiscoveryCertificatesDto.ts
  src/types/openapi/models/FunctionGroupCode.ts
  src/types/openapi/models/index.ts
  src/types/openapi/src/doc-openapi-czertainly-core.yaml
  src/utils/mock.ts
Labels: enhancement

#182 fix audit logs purging
  src/components/_pages/auditLogs/AuditLogsFilters/index.tsx
  src/components/_pages/auditLogs/auditLogs.module.scss
  src/components/_pages/auditLogs/index.tsx
  src/ducks/auditLogs-epics.ts
Labels: bug

#192 Add custom attributes to create and edit forms of objects
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/Attributes/AttributeEditor/index.tsx
  src/components/Layout/TabLayout/index.tsx
  src/components/_pages/acme-profiles/detail/index.tsx
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/authorities/detail/index.tsx
  src/components/_pages/authorities/form/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/compliance-profiles/detail/index.tsx
  src/components/_pages/compliance-profiles/form/index.tsx
  src/components/_pages/connectors/detail/index.tsx
  src/components/_pages/connectors/form/index.tsx
  src/components/_pages/credentials/detail/index.tsx
  src/components/_pages/credentials/form/index.tsx
  src/components/_pages/custom-attributes/detail/index.tsx
  src/components/_pages/discoveries/detail/index.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/components/_pages/entities/detail/index.tsx
  src/components/_pages/entities/form/index.tsx
  src/components/_pages/group/detail/index.tsx
  src/components/_pages/group/form/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/locations/form/index.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/components/_pages/ra-profiles/form/index.tsx
  src/components/_pages/roles/RoleForm/index.tsx
  src/components/_pages/roles/detail/index.tsx
  src/components/_pages/users/detail/index.tsx
  src/components/_pages/users/form/index.tsx
  src/ducks/customAttributes-epics.ts
  src/ducks/customAttributes.ts
  src/ducks/transform/attributes.ts
  src/resources/styles/_overrides.scss
  src/types/attributes.ts
  src/utils/attributes/attributeEditorMutators.ts
  src/utils/attributes/attributes.ts
  src/utils/validators.ts
Labels: enhancement

#200 Fix loading stored attributes content for attributes with callbacks
  src/components/Attributes/AttributeEditor/index.tsx
Labels: bug

#202 fix callback empty content and mappings of data
  src/components/Attributes/AttributeEditor/index.tsx
Labels: bug

#201 Add Token Profile and its management
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/components/_pages/token-profiles/detail/index.tsx
  src/components/_pages/token-profiles/form/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
  src/ducks/index.ts
  src/ducks/token-profiles-epics.ts
  src/ducks/token-profiles.ts
  src/ducks/tokens-epics.ts
  src/ducks/tokens.ts
  src/ducks/transform/token-profiles.ts
  src/types/token-profiles.ts
Labels: enhancement

#205 Add custom attributes widget to detail page of objects
  src/components/Attributes/AttributeEditor/index.tsx
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/Attributes/CustomAttributeWidget/index.tsx
  src/components/Input/DynamicContent/ContentDescriptorField/index.tsx
  src/components/Input/DynamicContent/ContentValueField/index.tsx
  src/components/Input/DynamicContent/index.tsx
  src/components/WidgetButtons/index.tsx
  src/components/_pages/acme-profiles/detail/index.tsx
  src/components/_pages/authorities/detail/index.tsx
  src/components/_pages/authorities/form/index.tsx
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/compliance-profiles/detail/index.tsx
  src/components/_pages/compliance-profiles/form/AddRuleWithAttributesDialogBody/index..tsx
  src/components/_pages/compliance-profiles/form/index.tsx
  src/components/_pages/connectors/detail/index.tsx
  src/components/_pages/connectors/form/index.tsx
  src/components/_pages/credentials/detail/index.tsx
  src/components/_pages/credentials/form/index.tsx
  src/components/_pages/cryptographic-keys/detail/RandomDataGeneration.tsx
  src/components/_pages/cryptographic-keys/detail/SignVerifyData.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/cryptographic-keys/form/index.tsx
  src/components/_pages/discoveries/detail/index.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/components/_pages/entities/detail/index.tsx
  src/components/_pages/entities/form/index.tsx
  src/components/_pages/group/detail/index.tsx
  src/components/_pages/group/form/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/locations/form/index.tsx
  src/components/_pages/ra-profiles/AcmeProtocolActivationDialogBody.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/components/_pages/ra-profiles/form/index.tsx
  src/components/_pages/roles/RoleForm/index.tsx
  src/components/_pages/roles/detail/index.tsx
  src/components/_pages/token-profiles/detail/index.tsx
  src/components/_pages/token-profiles/form/index.tsx
  src/components/_pages/tokens/TokenActivationDialogBody.tsx
  src/components/_pages/tokens/detail/index.tsx
  src/components/_pages/tokens/form/index.tsx
  src/components/_pages/users/detail/index.tsx
  src/components/_pages/users/form/index.tsx
  src/ducks/customAttributes-epics.ts
  src/ducks/customAttributes.ts
  src/ducks/transform/certificates.ts
  src/utils/validators.ts
Labels: enhancement
