Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-05, with the labels that each got.

#308 Add Intune configuration to SCEP profile
  src/components/Attributes/AttributeEditor/index.tsx
  src/components/Input/SwitchField/index.tsx
  src/components/_pages/scep-profiles/detail/index.tsx
  src/components/_pages/scep-profiles/form/index.tsx
  src/ducks/scep-profiles-epics.ts
  src/ducks/scep-profiles.ts
  src/types/openapi/apis/SCEPProfileManagementApi.ts
  src/types/openapi/models/ScepProfileDetailDto.ts
  src/types/openapi/models/ScepProfileDto.ts
  src/types/openapi/models/ScepProfileEditRequestDto.ts
  src/types/openapi/models/ScepProfileRequestDto.ts
Labels: new-feature

#310 Add SCEP URL and Intune enabled to SCEP list
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/SignVerifyData.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/scep-profiles/list/index.tsx
  src/ducks/cryptographic-operations.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/CryptographicOperationsControllerApi.ts
  src/types/openapi/models/KeyAlgorithm.ts
  src/types/openapi/models/KeyItemDetailDto.ts
  src/types/openapi/models/KeyItemDto.ts
  src/types/openapi/models/KeyType.ts
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/ScepProfileDetailDto.ts
  src/types/openapi/models/ScepProfileDto.ts
  src/types/openapi/models/SearchableFields.ts
  src/types/openapi/models/index.ts
Labels: enhancement, ignore-for-release

#312 SCEP challenge password optional when ECDSA certificate is selected
  src/components/_pages/scep-profiles/form/index.tsx
  src/types/openapi/models/ScepProfileEditRequestDto.ts
  src/types/openapi/models/ScepProfileRequestDto.ts
Labels: bug, ignore-for-release

#317 Add issue operation and disable inapplicable operations in certificate detail page for New certificate
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/scep-profiles/detail/index.tsx
  src/components/_pages/scep-profiles/form/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/ducks/transform/locations.ts
  src/types/locations.ts
  src/types/openapi/apis/ClientOperationsV2Api.ts
  src/types/openapi/models/CertificateInLocationDto.ts
  src/types/openapi/models/ClientCertificateSignRequestDto.ts
  src/types/openapi/models/ScepProfileDetailDto.ts
  src/types/openapi/models/ScepProfileDto.ts
  src/types/openapi/models/ScepProfileEditRequestDto.ts
  src/types/openapi/models/ScepProfileRequestDto.ts
  src/utils/certificate.ts
Labels: enhancement

#318 Small fixes and correct typos
  src/components/Dialog/Dialog.module.scss
  src/components/Dialog/index.tsx
  src/components/Input/SwitchField/index.tsx
  src/components/Layout/TabLayout/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/scep-profiles/detail/index.tsx
Labels: bug, ignore-for-release

#327 Unable to sign data and verify signature with Falcon key pair
  src/components/_pages/cryptographic-keys/detail/SignVerifyData.tsx
  src/types/cryptographic-operations.ts
  src/types/openapi/models/SignDataRequestDto.ts
  src/types/openapi/models/VerifyDataRequestDto.ts
Labels: bug, ignore-for-release

#335 Update RA profile for existing SCEP profile does not send selected RA…
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/scep-profiles/CertificateField.tsx
  src/components/_pages/scep-profiles/detail/index.tsx
  src/components/_pages/scep-profiles/form/index.tsx
  src/ducks/scep-profiles.ts
Labels: bug, ignore-for-release

#336 Fix layout of modal of push certificate to location action
  src/components/Dialog/index.tsx
  src/components/PagedList/PagedList.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/locations/detail/index.tsx
Labels: bug

#338 Fix cryptography key state on detail page
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/ducks/cryptographic-keys.ts
Labels: bug, ignore-for-release

#340 Fix changing state of keys and key items to respect key state model
  src/components/Alerts/Alerts.module.scss
  src/components/AppRouter.tsx
  src/components/Attributes/AttributeDescriptorViewer/index.tsx
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/FilterWidget/index.tsx
  src/components/Input/DynamicContent/index.tsx
  src/components/Layout/TabLayout/index.tsx
  src/components/PagedList/PagedList.tsx
  src/components/_pages/certificates/CertificateStatus/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/connectors/ConnectorStatus/index.tsx
  src/components/_pages/connectors/detail/index.tsx
  src/components/_pages/connectors/form/index.tsx
  src/components/_pages/cryptographic-keys/KeyStateBadge/index.tsx
  src/components/_pages/cryptographic-keys/KeyStateCircle/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/cryptographic-keys/form/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/custom-attributes/detail/index.tsx
  src/components/_pages/custom-attributes/form/index.tsx
  src/components/_pages/custom-attributes/list/index.tsx
  src/components/_pages/global-metadata/detail/index.tsx
  src/components/_pages/global-metadata/form/index.tsx
  src/components/_pages/global-metadata/list/ConnectorMetadataDialog.tsx
  src/components/_pages/global-metadata/list/index.tsx
  src/components/_pages/token-profiles/detail/index.tsx
  src/components/_pages/token-profiles/form/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/cryptographic-keys.ts
  src/ducks/enums.ts
  src/types/openapi/models/KeyState.ts
  src/utils/net.ts
Labels: enhancement

#342 Display widget under lock when user does not have permission or request fails
  src/components/PagedList/PagedList.tsx
  src/components/Widget/index.tsx
  src/components/WidgetButtons/index.tsx
  src/components/WidgetLock/WidgetLock.module.scss
  src/components/WidgetLock/index.tsx
  src/components/_pages/acme-accounts/list/index.tsx
  src/components/_pages/acme-profiles/list/index.tsx
  src/components/_pages/auditLogs/index.tsx
  src/components/_pages/authorities/list/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/compliance-profiles/list/index.tsx
  src/components/_pages/connectors/list/index.tsx
  src/components/_pages/credentials/list/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/custom-attributes/list/index.tsx
  src/components/_pages/dashboard/DashboardItem/CountBadge.tsx
  src/components/_pages/discoveries/list/index.tsx
  src/components/_pages/entities/list/index.tsx
  src/components/_pages/global-metadata/list/index.tsx
  src/components/_pages/group/list/index.tsx
  src/components/_pages/locations/list/index.tsx
  src/components/_pages/platform-settings/detail/index.tsx
  src/components/_pages/ra-profiles/list/index.tsx
  src/components/_pages/roles/list/index.tsx
  src/components/_pages/scep-profiles/list/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
  src/components/_pages/tokens/list/index.tsx
  src/components/_pages/users/list/index.tsx
  src/ducks/acme-accounts-epics.ts
  src/ducks/acme-profiles-epics.ts
  src/ducks/auditLogs-epics.ts
  src/ducks/authorities-epics.ts
  src/ducks/certificateGroups-epics.ts
  src/ducks/certificates-epics.ts
  src/ducks/compliance-profiles-epics.ts
  src/ducks/connectors-epic.ts
  src/ducks/credentials-epics.ts
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/customAttributes-epics.ts
  src/ducks/discoveries-epics.ts
  src/ducks/entities-epics.ts
  src/ducks/globalMetadata-epics.ts
  src/ducks/index.ts
  src/ducks/locations-epics.ts
  src/ducks/ra-profiles-epics.ts
  src/ducks/roles-epics.ts
  src/ducks/scep-profiles-epics.ts
  src/ducks/settings-epics.ts
  src/ducks/token-profiles-epics.ts
  src/ducks/tokens-epics.ts
  src/ducks/users-epics.ts
  src/ducks/widget-locks.ts
  src/types/widget-locks.ts
  src/utils/net.ts
Labels: enhancement
