Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-11, with the labels that each got.

#518 Fix sending of filled optional attributes in submitted form
  src/components/_pages/discoveries/detail/index.tsx
  src/utils/attributes/attributes.tsx
Labels: bug

#523 Fix redirect from dasboard to display certificates with unassigned group or RA profile
  src/components/_pages/dashboard/index.tsx
Labels: bug

#522 Fix label and tooltips for certificate state Pending Approval
  src/utils/certificate.tsx
Labels: bug, ignore-for-release

#530 Add icon to copy certificate content in PEM format to clipboard
  src/components/FlowChart/CustomFlowNode/index.tsx
  src/components/_pages/certificates/detail/certificateDetail.module.scss
  src/components/_pages/certificates/detail/index.tsx
Labels: enhancement

#526 Change owner of key to user reference
  src/components/_pages/acme-accounts/detail/index.tsx
  src/components/_pages/acme-accounts/list/index.tsx
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/acme-profiles/list/index.tsx
  src/components/_pages/approvals/list/index.tsx
  src/components/_pages/authorities/list/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/credentials/list/index.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/cryptographic-keys/form/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/discoveries/list/index.tsx
  src/components/_pages/entities/list/index.tsx
  src/components/_pages/locations/list/index.tsx
  src/components/_pages/ra-profiles/list/index.tsx
  src/components/_pages/scep-profiles/form/index.tsx
  src/components/_pages/scep-profiles/list/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
  src/components/_pages/tokens/list/index.tsx
  src/ducks/transform/acme-profiles.ts
  src/ducks/transform/ra-profiles.ts
  src/ducks/transform/scep-profiles.ts
  src/types/acme-profiles.ts
  src/types/openapi/models/AcmeAccountListResponseDto.ts
  src/types/openapi/models/AcmeAccountResponseDto.ts
  src/types/openapi/models/AcmeProfileDto.ts
  src/types/openapi/models/AcmeProfileListDto.ts
  src/types/openapi/models/CertificateUpdateObjectsDto.ts
  src/types/openapi/models/EditKeyRequestDto.ts
  src/types/openapi/models/KeyDetailDto.ts
  src/types/openapi/models/KeyDto.ts
  src/types/openapi/models/KeyItemDto.ts
  src/types/openapi/models/KeyRequestDto.ts
  src/types/openapi/models/MultipleCertificateObjectUpdateDto.ts
  src/types/openapi/models/RaProfileDto.ts
  src/types/openapi/models/ScepProfileDetailDto.ts
  src/types/openapi/models/ScepProfileDto.ts
  src/types/openapi/models/SimplifiedRaProfileDto.ts
  src/types/ra-profiles.ts
  src/types/scep-profiles.ts
Labels: enhancement

#531 Fix state when the request is approved from approval detail page
  src/ducks/approvals.ts
Labels: bug

#533 Add icon to copy certificate request content in PEM format to clipboard
  src/components/FlowChart/CustomFlowNode/index.tsx
  src/components/_pages/certificates/detail/index.tsx
Labels: enhancement

#534 Update release version to 2.10.0
  package.json
Labels: ignore-for-release

#536 Fix style of Connect button when creating new connector
  src/components/_pages/connectors/form/index.tsx
  src/components/_pages/cryptographic-keys/form/index.tsx
Labels: bug
