Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-03, with the labels that each got.

#246 Add management of platform settings
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/CertificateAttributes/index.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateRenewDialog/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/settings/detail/index.tsx
  src/components/_pages/settings/form/index.tsx
  src/ducks/index.ts
  src/ducks/settings-epics.ts
  src/ducks/settings.ts
  src/ducks/transform/settings.ts
  src/ducks/utilsCertificate-epics.ts
  src/ducks/utilsCertificateRequest-epics.ts
  src/ducks/utilsOid-epics.ts
  src/store.ts
  src/types/attributes.ts
  src/types/settings.ts
Labels: enhancement

#248 Update discovery detail to show discovered certificates categorized
  src/components/CustomTable/PagedCustomTable.tsx
  src/components/_pages/discoveries/detail/DiscoveryCertificates.tsx
  src/components/_pages/discoveries/detail/index.tsx
  src/ducks/discoveries-epics.ts
  src/ducks/discoveries.ts
  src/ducks/transform/discoveries.ts
  src/types/discoveries.ts
Labels: enhancement

#252 Change discovery certificates table to tabs layout
  src/components/Layout/TabLayout/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/discoveries/detail/DiscoveryCertificates.tsx
Labels: ignore-for-release

#253 Possibility to render only active tab content
  src/components/Layout/TabLayout/index.tsx
  src/components/_pages/discoveries/detail/DiscoveryCertificates.tsx
Labels: bug, ignore-for-release

#254 Fix login redirect
  src/components/AppRedirect.tsx
  src/components/AppRouter.tsx
  src/ducks/startup-epics.ts
Labels: bug, ignore-for-release

#255 Add file upload component
  src/components/Input/FileUpload/FileUpload.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateRenewDialog/index.tsx
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/cryptographic-keys/detail/SignVerifyData.tsx
Labels: enhancement, ignore-for-release

#260 Add search filters for custom and metadata attributes
  package-lock.json
  src/components/FilterWidget/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/cryptographic-keys.ts
  src/ducks/transform/certificates.ts
  src/types/certificate.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/CertificateInventoryApi.ts
  src/types/openapi/apis/CryptographicKeyControllerApi.ts
  src/types/openapi/models/SearchFieldDataByGroupDto.ts
  src/types/openapi/models/SearchFieldDataDto.ts
  src/types/openapi/models/SearchFilterRequestDto.ts
  src/types/openapi/models/SearchableFieldType.ts
  src/types/openapi/models/SearchableFields.ts
  src/types/openapi/models/index.ts
  yarn.lock
Labels: enhancement

#263 Change app header to be fixed on scroll
  src/components/Layout/Header/index.tsx
Labels: enhancement, ignore-for-release

#261 Change table to not expand row when there is no detail information
  src/components/_pages/certificates/detail/index.tsx
Labels: enhancement, ignore-for-release

#262 Format displayed certificate ASN.1 structure data in certificate detail
  src/components/_pages/certificates/Asn1Dialog/Asn1Dialog.tsx
  src/components/_pages/certificates/detail/index.tsx
Labels: enhancement, ignore-for-release

#267 Update CZERTAINLY styles
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Header/index.tsx
  src/components/Layout/Sidebar/LinksGroup/LinksGroup.module.scss
  src/components/Layout/Sidebar/Sidebar.module.scss
  src/components/Layout/Sidebar/index.tsx
  src/components/Layout/index.tsx
  src/resources/images/czertainly-chain.png
  src/resources/styles/_variables.scss
Labels: enhancement

#272 Add certificate custom attributes to the issue certificate to location dialog
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/ducks/customAttributes-epics.ts
  src/ducks/customAttributes.ts
  src/types/locations.ts
  src/types/openapi/models/IssueToLocationRequestDto.ts
Labels: enhancement, ignore-for-release

#275 Include legacy authority provider in authority form
  src/components/_pages/authorities/form/index.tsx
Labels: bug, ignore-for-release

#278 Refactor and fix certificate handling
  package-lock.json
  package.json
  src/components/Attributes/CustomAttributeWidget/index.tsx
  src/components/CertificateAttributes/index.tsx
  src/components/Input/DynamicContent/ContentValueField/index.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/authorities/form/index.tsx
  src/components/_pages/certificates/Asn1Dialog/Asn1Dialog.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/credentials/form/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/components/_pages/entities/form/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/locations/form/index.tsx
  src/components/_pages/tokens/form/index.tsx
  src/utils/validators.ts
Labels: bug, ignore-for-release

#280 Update release version to 2.7.0
  package.json
Labels: ignore-for-release
