Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-06, with the labels that each got.

#350 Fix Audit logs pagination to show correct total items count
  src/components/_pages/auditLogs/index.tsx
  src/ducks/auditLogs-epics.ts
  src/ducks/auditLogs.ts
  src/types/openapi/models/AuditLogDto.ts
  src/types/openapi/models/AuditLogFilter.ts
  src/types/openapi/models/AuditLogResponseDto.ts
Labels: bug

#352 Update version to 2.8.0
  package.json
Labels: ignore-for-release

#349 Add refresh action to widgets
  src/components/Attributes/AttributeEditor/index.tsx
  src/components/Attributes/CustomAttributeWidget/index.tsx
  src/components/FilterWidget/index.tsx
  src/components/PagedList/PagedList.tsx
  src/components/Widget/Widget.module.scss
  src/components/Widget/index.tsx
  src/components/WidgetLock/index.tsx
  src/components/_pages/acme-accounts/detail/index.tsx
  src/components/_pages/acme-accounts/list/index.tsx
  src/components/_pages/acme-profiles/detail/index.tsx
  src/components/_pages/acme-profiles/list/index.tsx
  src/components/_pages/auditLogs/index.tsx
  src/components/_pages/authorities/detail/index.tsx
  src/components/_pages/authorities/list/index.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/compliance-profiles/detail/index.tsx
  src/components/_pages/compliance-profiles/list/index.tsx
  src/components/_pages/connectors/detail/index.tsx
  src/components/_pages/connectors/form/index.tsx
  src/components/_pages/connectors/list/index.tsx
  src/components/_pages/credentials/detail/index.tsx
  src/components/_pages/credentials/list/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/custom-attributes/detail/index.tsx
  src/components/_pages/custom-attributes/list/index.tsx
  src/components/_pages/dashboard/DashboardItem/CountBadge.tsx
  src/components/_pages/dashboard/DashboardItem/DonutChart.tsx
  src/components/_pages/discoveries/detail/DiscoveryCertificates.tsx
  src/components/_pages/discoveries/detail/index.tsx
  src/components/_pages/entities/detail/index.tsx
  src/components/_pages/global-metadata/detail/index.tsx
  src/components/_pages/global-metadata/list/index.tsx
  src/components/_pages/group/detail/index.tsx
  src/components/_pages/group/list/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/platform-settings/detail/index.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/components/_pages/ra-profiles/list/index.tsx
  src/components/_pages/roles/RolePermissionsEdior/index.tsx
  src/components/_pages/roles/detail/index.tsx
  src/components/_pages/roles/list/index.tsx
  src/components/_pages/scep-profiles/detail/index.tsx
  src/components/_pages/scep-profiles/list/index.tsx
  src/components/_pages/token-profiles/detail/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
  src/components/_pages/tokens/detail/index.tsx
  src/components/_pages/tokens/list/index.tsx
  src/components/_pages/user-profile/detail/index.tsx
  src/components/_pages/users/detail/index.tsx
  src/components/_pages/users/form/index.tsx
  src/components/_pages/users/list/index.tsx
  src/ducks/customAttributes-epics.ts
Labels: enhancement

#345 Change owner of certificate to user reference
  src/components/_pages/certificates/CertificateOwnerDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/types/openapi/models/CertificateUpdateObjectsDto.ts
  src/types/openapi/models/MultipleCertificateObjectUpdateDto.ts
Labels: enhancement

#353 Use callbacks for location connector attributes
  src/components/_pages/locations/form/index.tsx
Labels: ignore-for-release

#361 Fix create/update user form preventing saving user
  src/components/PagedList/PagedList.tsx
  src/components/Widget/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/users/form/index.tsx
Labels: bug, ignore-for-release

#365 Group Renovate dependencies updates
  .github/workflows/build.yml
  .github/workflows/workflow_run_pruner.yml
  Dockerfile
  package-lock.json
Labels: dependencies, ignore-for-release

#372 Management of scheduled jobs
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/PagedList/PagedList.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/discoveries/list/index.tsx
  src/components/_pages/entities/list/index.tsx
  src/components/_pages/locations/list/index.tsx
  src/components/_pages/scheduler/detail/SchedulerJobHistory.tsx
  src/components/_pages/scheduler/detail/index.tsx
  src/components/_pages/scheduler/list/index.tsx
  src/ducks/filters.ts
  src/ducks/index.ts
  src/ducks/scheduler-epics.ts
  src/ducks/scheduler.ts
  src/ducks/transform/scheduler.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/DiscoveryManagementApi.ts
  src/types/openapi/apis/ScheduledJobsManagementApi.ts
  src/types/openapi/apis/index.ts
  src/types/openapi/models/PaginationRequestDto.ts
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/ScheduleDiscoveryDto.ts
  src/types/openapi/models/ScheduleDiscoveryRequest.ts
  src/types/openapi/models/ScheduledJobDetailDto.ts
  src/types/openapi/models/ScheduledJobDto.ts
  src/types/openapi/models/ScheduledJobHistoryDto.ts
  src/types/openapi/models/ScheduledJobHistoryResponseDto.ts
  src/types/openapi/models/ScheduledJobsResponseDto.ts
  src/types/openapi/models/SchedulerJobExecutionStatus.ts
  src/types/openapi/models/SchedulerJobInfoDto.ts
  src/types/openapi/models/index.ts
  src/types/scheduler.ts
  src/types/widget-locks.ts
  src/utils/dateUtil.ts
Labels: new-feature

#375 Support for scheduling of discoveries
  package-lock.json
  package.json
  src/components/Input/TextField/index.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/doc-openapi-czertainly-core.yaml
  src/ducks/discoveries-epics.ts
  src/ducks/discoveries.ts
Labels: new-feature

#376 When utils service is not configured cannot create/edit user with uploading certificate option
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
  src/components/_pages/users/form/index.tsx
Labels: bug, ignore-for-release

#378 Small changes in scheduled jobs
  src/components/AppRouter.tsx
  src/components/BooleanBadge/BooleanBadge.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/PagedList/PagedList.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/components/_pages/scheduler/detail/SchedulerJobHistory.tsx
  src/components/_pages/scheduler/detail/index.tsx
  src/components/_pages/scheduler/list/index.tsx
  src/ducks/discoveries-epics.ts
  src/ducks/discoveries.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/Resource.ts
  src/types/openapi/models/ScheduleDiscoveryDto.ts
  src/types/openapi/models/ScheduledJobDetailDto.ts
  src/types/openapi/models/ScheduledJobDto.ts
  src/types/openapi/models/ScheduledJobHistoryDto.ts
  src/utils/dateUtil.tsx
Labels: enhancement, ignore-for-release

#379 Fix new line in tooltip
  src/utils/dateUtil.tsx
Labels: ignore-for-release

#380 Link renewed/rekeyed certificate to its predecessor
  src/components/_pages/certificates/detail/index.tsx
  src/doc-openapi-czertainly-core.yaml
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/models/CertificateDetailDto.ts
Labels: enhancement

#383 Add issue and revoke attributes to certificate
  src/components/_pages/certificates/detail/index.tsx
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateRequestDto.ts
  src/types/openapi/models/index.ts
Labels: enhancement

#385 Add widget to display related certificates in detail page
  src/components/Layout/TabLayout/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateEventHistoryDto.ts
Labels: enhancement
