Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2023-09, with the labels that each got.

#476 Update release version to 2.9.0
  package.json
Labels: ignore-for-release

#477 Fix scheduler CRON expression validation
  src/components/_pages/discoveries/form/index.tsx
  src/utils/validators.ts
Labels: bug

#480 Fix upload certificate input when creating and updating user
  .gitignore
  src/components/_pages/users/form/index.tsx
Labels: bug

#484 Update attribute viewer for file content type to display file info
  src/utils/attributes/attributes.tsx
Labels: enhancement

#481 Update file upload component to allow user to paste content
  src/components/Input/FileUpload/FileUpload.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateRenewDialog/index.tsx
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/cryptographic-keys/detail/SignVerifyData.tsx
Labels: enhancement

#485 Update connector detail page to display health check response parts
  src/components/_pages/connectors/detail/index.tsx
Labels: enhancement

#487 Fix disabling certificate operations based on certificate status
  src/components/Widget/index.tsx
  src/components/_pages/certificates/detail/index.tsx
Labels: bug
