Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2024-11, with the labels that each got.

#804 Fix URL of endpoint for getting locations search filters
  src/types/openapi/apis/LocationManagementApi.ts
Labels: bug, ignore-for-release

#805 Fix dashboard stats and replace basic constraints with subject type property
  package-lock.json
  src/components/_pages/certificates/CertificateStatus/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/dashboard/index.tsx
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateSubjectType.ts
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/StatisticsDto.ts
  src/types/openapi/models/index.ts
  src/utils/certificate.tsx
Labels: bug

#807 Release 2.13.1
  package-lock.json
  package.json
  src/components/_pages/certificates/CertificateStatus/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/dashboard/index.tsx
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/LocationManagementApi.ts
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateSubjectType.ts
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/StatisticsDto.ts
  src/types/openapi/models/index.ts
  src/utils/certificate.tsx
Labels: ignore-for-release

#810 Update audit logs inventory to support new audit logs structure and filters
  openapitools.json
  package-lock.json
  src/components/_pages/auditLogs/AuditLogsFilters/auditLogsFilters.module.scss
  src/components/_pages/auditLogs/AuditLogsFilters/index.tsx
  src/components/_pages/auditLogs/index.tsx
  src/ducks/auditLogs-epics.ts
  src/ducks/auditLogs.ts
  src/ducks/filters.ts
  src/ducks/transform/auditLogs.ts
  src/types/auditLogs.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/AuditLogApi.ts
  src/types/openapi/models/ActorRecord.ts
  src/types/openapi/models/ActorType.ts
  src/types/openapi/models/AddUserRequestDto.ts
  src/types/openapi/models/AuditLogDto.ts
  src/types/openapi/models/AuditLogFilter.ts
  src/types/openapi/models/AuthMethod.ts
  src/types/openapi/models/Module.ts
  src/types/openapi/models/Operation.ts
  src/types/openapi/models/OperationResult.ts
  src/types/openapi/models/Pageable.ts
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/Resource.ts
  src/types/openapi/models/ResourceDetailDto.ts
  src/types/openapi/models/ResourceRecord.ts
  src/types/openapi/models/RuleTriggerHistoryDto.ts
  src/types/openapi/models/SourceRecord.ts
  src/types/openapi/models/index.ts
Labels: enhancement

#812 Change audit logs inventory UI to display additional information in modal window
  src/components/_pages/auditLogs/index.tsx
Labels: enhancement, ignore-for-release
