Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2024-02, with the labels that each got.

#577 Fix creating object in modal dialog in form on select behaviour
  src/components/_pages/certificates/form/RenderRequestKey.tsx
Labels: bug

#578 Remove visible property and restrict creating custom attribute without default content
  src/components/Input/DynamicContent/ContentDescriptorField/index.tsx
  src/components/Input/DynamicContent/index.tsx
  src/components/_pages/custom-attributes/form/index.tsx
Labels: enhancement

#582 Fix setting value of credential attribute input in edit form depending on callback
  src/components/Attributes/AttributeEditor/index.tsx
Labels: bug

#583 Update release version to 2.11.0
  package.json
Labels: ignore-for-release

#574 Do not send request for internal notifications when user is logged out
  src/components/_pages/notifications/list/index.tsx
  src/ducks/app-redirect.ts
  src/ducks/auth.ts
  src/ducks/index.ts
  src/ducks/notifications-epics.ts
  src/ducks/startup-epics.ts
Labels: bug

#587 Fix custom attributes of create/edit user form getting replaced by certificate custom attributes
  src/components/_pages/certificates/CertificateUploadDialog/index.tsx
Labels: bug
