Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2024-12, with the labels that each got.

#814 Add total certificates downloaded and info dialog about processing error to discovery detail page
  src/components/_pages/discoveries/detail/DiscoveryCertificates.tsx
  src/components/_pages/discoveries/detail/index.tsx
  src/utils/dateUtil.tsx
Labels: enhancement

#815 Add Auth method column to audit logs table
  src/components/_pages/auditLogs/index.tsx
Labels: enhancement, ignore-for-release

#808 Allow editing CRON expression of existing non-system scheduled job
  src/components/WidgetButtons/index.tsx
  src/components/_pages/scheduler/detail/index.tsx
  src/ducks/scheduler-epics.ts
  src/ducks/scheduler.ts
  src/types/openapi/apis/ScheduledJobsManagementApi.ts
Labels: new-feature

#816 Updates for release 2.14.0
  package.json
Labels: ignore-for-release

#817 Release 2.14.0
  openapitools.json
  package-lock.json
  package.json
  src/components/WidgetButtons/index.tsx
  src/components/_pages/auditLogs/AuditLogsFilters/auditLogsFilters.module.scss
  src/components/_pages/auditLogs/AuditLogsFilters/index.tsx
  src/components/_pages/auditLogs/index.tsx
  src/components/_pages/discoveries/detail/DiscoveryCertificates.tsx
  src/components/_pages/discoveries/detail/index.tsx
  src/components/_pages/discoveries/list/index.tsx
  src/components/_pages/scheduler/detail/index.tsx
  src/ducks/auditLogs-epics.ts
  src/ducks/auditLogs.ts
  src/ducks/filters.ts
  src/ducks/scheduler-epics.ts
  src/ducks/scheduler.ts
  src/ducks/transform/auditLogs.ts
  src/types/auditLogs.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/AuditLogApi.ts
  src/types/openapi/apis/ScheduledJobsManagementApi.ts
  src/types/openapi/models/ActorRecord.ts
  src/types/openapi/models/ActorType.ts
  src/types/openapi/models/AddUserRequestDto.ts
  src/types/openapi/models/AuditLogDto.ts
  src/types/openapi/models/AuditLogFilter.ts
  src/types/openapi/models/AuthMethod.ts
  src/types/openapi/models/Module.ts
  src/types/openapi/models/Operation.ts
  src/types/openapi/models/OperationResult.ts
  src/types/openapi/models/Pageable.ts
  src/types/openapi/models/PlatformEnum.ts
  src/types/openapi/models/Resource.ts
  src/types/openapi/models/ResourceDetailDto.ts
  src/types/openapi/models/ResourceRecord.ts
  src/types/openapi/models/RuleTriggerHistoryDto.ts
  src/types/openapi/models/SourceRecord.ts
  src/types/openapi/models/index.ts
  src/utils/dateUtil.tsx
Labels: ignore-for-release
