Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2024-08, with the labels that each got.

#745 Remove unused packages
  package-lock.json
  package.json
Labels: dependencies

#763 Update minor versions of dependencies
  .github/workflows/publish_docker_3key.yml
  .github/workflows/publish_docker_czertainly.yml
  .github/workflows/publish_harbor_3key.yml
  package-lock.json
  package.json
Labels: dependencies

#764 Fix marked.parse error
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
Labels: ignore-for-release

#765 Update dependency web-vitals to v4
  src/reportWebVitals.ts
Labels: ignore-for-release

#767 Update discovery detail page to use tabbed layout
  src/components/_pages/discoveries/detail/index.tsx
Labels: enhancement

#719 Update colors for the dashboard graphs to be distinguishable
  src/components/_pages/dashboard/index.tsx
  src/utils/dashboard.tsx
Labels: enhancement

#769 Fix Dockerfile warnings
  Dockerfile
Labels: ignore-for-release

#766 Add documentation for fixing type errors in generated API types
  README.md
Labels: documentation, ignore-for-release

#768 Fix browser reported errors and issues
  cypress/component/Attributes/AttributeEditor/AttributeEditor.cy.tsx
  cypress/component/_pages/users/form/form.cy.tsx
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/CustomTable/index.tsx
  src/components/FilterWidget/index.tsx
  src/components/FilterWidgetRuleAction/index.tsx
  src/components/WidgetButtons/index.tsx
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/actions/form/index.tsx
  src/components/_pages/approval-profiles/form/approval-step-field.tsx
  src/components/_pages/auditLogs/AuditLogsFilters/index.tsx
  src/components/_pages/authorities/form/index.tsx
  src/components/_pages/certificates/CertificateGroupDialog/index.tsx
  src/components/_pages/certificates/CertificateRAProfileDialog/index.tsx
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/form/RenderRequestKey.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/cmp-profiles/form/index.tsx
  src/components/_pages/conditions/form/index.tsx
  src/components/_pages/connectors/form/index.tsx
  src/components/_pages/credentials/form/index.tsx
  src/components/_pages/cryptographic-keys/form/index.tsx
  src/components/_pages/custom-attributes/form/index.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/components/_pages/entities/form/index.tsx
  src/components/_pages/executions/form/index.tsx
  src/components/_pages/locations/detail/index.tsx
  src/components/_pages/locations/form/index.tsx
  src/components/_pages/notifications/notification-instance-form/index.tsx
  src/components/_pages/notifications/notifications-setting/index.tsx
  src/components/_pages/ra-profiles/AssociateApprovalProfileDialogBody.tsx
  src/components/_pages/ra-profiles/ProtocolActivationDialogBody.tsx
  src/components/_pages/ra-profiles/form/index.tsx
  src/components/_pages/roles/RoleForm/index.tsx
  src/components/_pages/rules/form/index.tsx
  src/components/_pages/scep-profiles/CertificateField.tsx
  src/components/_pages/scep-profiles/form/index.tsx
  src/components/_pages/token-profiles/form/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
  src/components/_pages/tokens/form/index.tsx
  src/components/_pages/triggers/form/index.tsx
  src/components/_pages/users/form/index.tsx
  src/ducks/transform/rules.tsx
Labels: bug, ignore-for-release

#772 Fix key console error in Widget Buttons component
  src/components/WidgetButtons/index.tsx
Labels: bug, ignore-for-release

#777 Fix blank page issue when deleting a certificate
  src/components/FlowChart/index.tsx
  src/components/WidgetButtons/index.tsx
Labels: bug, ignore-for-release

#778 Fix create discovery form and other forms due to input IDs
  src/components/_pages/actions/form/index.tsx
  src/components/_pages/conditions/form/index.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/components/_pages/executions/form/index.tsx
  src/components/_pages/notifications/notification-instance-form/index.tsx
  src/components/_pages/tokens/form/index.tsx
  src/components/_pages/triggers/form/index.tsx
Labels: bug, ignore-for-release

#775 Add attribute constraint validation of type RANGE
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
Labels: bug

#722 Fix access denied handling for attributes and permissions
  src/components/Attributes/CustomAttributeWidget/index.tsx
  src/ducks/auth-epics.ts
  src/ducks/certificateGroups-epics.ts
  src/ducks/customAttributes-epics.ts
  src/ducks/token-profiles-epics.ts
  src/types/user-interface.tsx
Labels: bug

#783 Add attribute description to Custom Attribute widget input
  src/components/Attributes/CustomAttributeWidget/customAttributeWidget.module.scss
  src/components/Attributes/CustomAttributeWidget/index.tsx
Labels: enhancement

#786 Fix sending content of attributes of content type date and datetime in request payload from attribute editor
  src/utils/attributes/attributes.tsx
Labels: bug

#788 Fix browser issue in inventory filter
  src/components/FilterWidget/index.tsx
Labels: bug, ignore-for-release

#787 Use enum item label in filter value select in inventory filters of enum properties
  src/components/FilterWidget/index.tsx
Labels: bug

#789 Fix date picker value selection in inventory filters
  src/components/FilterWidget/index.tsx
  src/utils/dateUtil.tsx
Labels: bug, ignore-for-release

#791 Fix custom attribute date time picker in filters
  src/components/FilterWidget/index.tsx
Labels: bug, ignore-for-release
