Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2024-06, with the labels that each got.

#708 Fix rendering of boolean flags to toggle and rendering of custom attribute viewer
  cypress/component/Attributes/CustomAttributeWidget/CustomAttributeWidget.cy.tsx
  src/components/Alerts/index.tsx
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/Attributes/AttributeEditor/index.tsx
  src/components/Input/DynamicContent/ContentValueField/index.tsx
  src/components/SwitchWidget/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/triggers/details/index.tsx
  src/components/_pages/triggers/details/triggerDetails.module.scss
  src/components/_pages/triggers/form/index.tsx
  src/ducks/alert-slice.ts
  src/ducks/ra-profiles-epics.ts
  src/types/alerts.ts
  src/utils/attributes/attributes.tsx
  src/utils/dateUtil.tsx
Labels: bug, ignore-for-release

#709 Fix formatting of condition and execution items data and its badge visualization
  src/components/ConditionAndExecutionItemsViewer/index.tsx
  src/components/ExecutionConditionItemsList/ConditionsItemsList/index.tsx
  src/components/ExecutionConditionItemsList/ExecutionsItemsList/index.tsx
  src/components/FilterWidget/index.tsx
  src/components/FilterWidgetRuleAction/index.tsx
  src/types/openapi/models/DiscoveryStatus.ts
  src/types/openapi/models/SearchFieldDataDto.ts
  src/types/openapi/models/TriggerHistoryRecordDto.ts
  src/utils/common-utils.ts
  src/utils/dateUtil.tsx
Labels: bug, ignore-for-release

#711 Release version 2.12.0
  package.json
Labels: ignore-for-release

#718 Fix pagination information when no items are displayed in table
  src/components/CustomTable/index.tsx
Labels: bug

#714 Implement CMP Profile management
  package-lock.json
  src/api.ts
  src/components/AppRouter.tsx
  src/components/Attributes/CustomAttributeWidget/index.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/cmp-profiles/details/index.tsx
  src/components/_pages/cmp-profiles/form/cmpForm.module.scss
  src/components/_pages/cmp-profiles/form/index.tsx
  src/components/_pages/cmp-profiles/list/index.tsx
  src/ducks/cmp-profiles-epics.ts
  src/ducks/cmp-profiles.ts
  src/ducks/index.ts
  src/ducks/initial-state.ts
  src/ducks/reducers.ts
  src/ducks/transform/cmp-profiles.ts
  src/types/cmp-profiles.ts
  src/types/user-interface.tsx
Labels: new-feature
