Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2024-09, with the labels that each got.

#794 Fix deleting trigger action from Flow view
  src/components/FlowChart/index.tsx
  src/ducks/transform/rules.tsx
Labels: bug

#795 Fix react flow custom nodes positioning
  src/components/FlowChart/index.tsx
Labels: bug, ignore-for-release

#796 Update build action
  .github/workflows/build.yml
Labels: ignore-for-release

#798 Updates for release 2.13.0
  README.md
  package.json
Labels: ignore-for-release
