Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2024-05, with the labels that each got.

#682 Update certificate operations actions to include certificate request format parameter
  src/components/_pages/certificates/CertificateRekeyDialog/index.tsx
  src/components/_pages/certificates/CertificateRenewDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/types/openapi/models/CertificateRequestFormat.ts
  src/types/openapi/models/ClientCertificateRekeyRequestDto.ts
  src/types/openapi/models/ClientCertificateRenewRequestDto.ts
  src/types/openapi/models/ClientCertificateRequestDto.ts
  src/types/openapi/models/ClientCertificateSignRequestDto.ts
  src/types/openapi/models/DataAttribute.ts
Labels: enhancement

#683 Fix redirecting after delete of trigger and minor UI changes
  src/components/ConditionGroupsList/GroupActionsViewer/index.tsx
  src/components/ConditionsViewer/index.tsx
  src/components/_pages/triggers/details/index.tsx
  src/components/_pages/triggers/list/index.tsx
  src/ducks/rules-epics.ts
Labels: bug, ignore-for-release

#687 Assign multiple groups to certificate, keys and users
  src/components/_pages/certificates/CertificateGroupDialog/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/cryptographic-keys/form/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/discoveries/form/index.tsx
  src/components/_pages/triggers/form/index.tsx
  src/components/_pages/users/detail/index.tsx
  src/components/_pages/users/form/index.tsx
  src/components/_pages/users/list/index.tsx
  src/ducks/certificates-epics.ts
  src/ducks/certificates.ts
  src/ducks/rules-epics.ts
  src/ducks/rules.ts
  src/ducks/transform/certificates.tsx
  src/types/certificate.ts
  src/types/cryptographic-keys.ts
  src/types/openapi/models/AddUserRequestDto.ts
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateDto.ts
  src/types/openapi/models/CertificateUpdateObjectsDto.ts
  src/types/openapi/models/DiscoveryHistoryDetailDto.ts
  src/types/openapi/models/EditKeyRequestDto.ts
  src/types/openapi/models/GroupDto.ts
  src/types/openapi/models/KeyDetailDto.ts
  src/types/openapi/models/KeyDto.ts
  src/types/openapi/models/KeyItemDto.ts
  src/types/openapi/models/KeyRequestDto.ts
  src/types/openapi/models/MultipleCertificateObjectUpdateDto.ts
  src/types/openapi/models/NameAndUuidDto.ts
  src/types/openapi/models/ResourceDto.ts
  src/types/openapi/models/RuleTriggerDetailDto.ts
  src/types/openapi/models/RuleTriggerDto.ts
  src/types/openapi/models/RuleTriggerRequestDto.ts
  src/types/openapi/models/UpdateRuleTriggerRequestDto.ts
  src/types/openapi/models/UpdateUserRequestDto.ts
  src/types/openapi/models/UserDetailDto.ts
  src/types/openapi/models/UserDto.ts
Labels: enhancement

#691 Fix styles for widget buttons and custom table's add new row button
  src/components/CustomTable/NewRowWidget/NewRowWidget.module.scss
  src/components/CustomTable/NewRowWidget/index.tsx
  src/components/WidgetButtons/index.tsx
Labels: ignore-for-release

#690 Fix editing user does not fill custom attributes inputs with existing content
  cypress.d.ts
  cypress/component/_pages/users/form/form.cy.tsx
  cypress/component/_pages/users/form/mock-data.ts
  cypress/support/commands.tsx
  src/components/_pages/users/form/index.tsx
  src/ducks/users.ts
Labels: bug, ignore-for-release

#692 Fix custom attribute widget input alignment
  src/components/Attributes/AttributeViewer/index.tsx
Labels: bug

#698 Fix Token Profile Name in forms
  src/components/_pages/token-profiles/form/index.tsx
  src/components/_pages/token-profiles/list/index.tsx
Labels: bug

#704 Add Processing status to DiscoveryStatus enum
  src/components/_pages/discoveries/DiscoveryStatus/index.tsx
  src/types/openapi/models/DiscoveryStatus.ts
Labels: enhancement

#705 Fix update of execution and condition items when deleting
  src/components/FilterWidget/index.tsx
  src/components/FilterWidgetRuleAction/index.tsx
Labels: bug, ignore-for-release

#707 Remove unnecessary API requests for rule and action description editing
  src/components/_pages/actions/detail/index.tsx
  src/components/_pages/rules/detail/index.tsx
Labels: bug, ignore-for-release

#706 Fix styles and alignment in various components
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/Attributes/CodeBlock/index.tsx
  src/components/Input/DynamicContent/ContentDescriptorField/index.tsx
  src/components/WidgetButtons/index.tsx
  src/components/_pages/discoveries/detail/DiscoveryCertificates.tsx
  src/components/_pages/discoveries/detail/TriggerHistorySummaryViewer/index.tsx
  src/components/_pages/discoveries/detail/discoveryCertificates.module.scss
  src/components/_pages/triggers/details/index.tsx
Labels: bug, ignore-for-release
