Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2025-03, with the labels that each got.

#863 Updates to release 2.14.1
  package.json
Labels: ignore-for-release

#866 Add authentication settings
  src/components/AppRouter.tsx
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/Input/CustomSelect/CustomSelect.module.scss
  src/components/Input/CustomSelect/index.tsx
  src/components/Input/TextField/index.tsx
  src/components/Layout/Sidebar/index.tsx
  src/components/_pages/auth-settings/detail/index.tsx
  src/components/_pages/auth-settings/form/index.tsx
  src/components/_pages/auth-settings/index.tsx
  src/ducks/auth-settings-epics.ts
  src/ducks/auth-settings.ts
  src/ducks/index.ts
  src/ducks/reducers.ts
  src/ducks/transform/auth-settings.ts
  src/types/auth-settings.ts
  src/types/user-interface.tsx
  src/utils/oauth2Providers.tsx
  src/utils/validators.ts
Labels: new-feature

#875 CI/CD dependencies updates
  .github/workflows/build.yml
  .github/workflows/cypress-component.yml
  .github/workflows/publish_docker_3key.yml
  .github/workflows/publish_docker_czertainly.yml
  .github/workflows/publish_harbor_3key.yml
  Dockerfile
  package-lock.json
  package.json
Labels: dependencies

#877 Transition the app from CRA to Vite bundler
  .eslintignore
  .eslintrc
  config-overrides.js
  cypress.config.js
  cypress.d.ts
  cypress/component/CustomTable/CustomTable.cy.tsx
  cypress/component/Widget/Widget.cy.tsx
  cypress/support/commands.tsx
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/AppLogin/AppLogin.tsx
  src/components/ExecutionConditionItemsList/executionConditionItemsList.module.scss
  src/components/FilterWidget/index.tsx
  src/components/FlowChart/CustomFlowNode/customFlowNode.module.scss
  src/components/FlowChart/flowChart.module.scss
  src/components/Input/TextField/TextField.module.scss
  src/components/Layout/Footer/Footer.module.scss
  src/components/Layout/Header/Header.module.scss
  src/components/Layout/Layout.module.scss
  src/components/Layout/Sidebar/LinksGroup/LinksGroup.module.scss
  src/components/Layout/Sidebar/Sidebar.module.scss
  src/components/Widget/Widget.module.scss
  src/components/_pages/actions/detail/rulesDetail.module.scss
  src/components/_pages/actions/list/executions-list-component/actionGroupsList.module.scss
  src/components/_pages/certificates/detail/CertificateDownloadForm.tsx
  src/components/_pages/certificates/detail/certificateDetail.module.scss
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/connectors/detail/connectorDetails.module.scss
  src/components/_pages/custom-attributes/detail/customAttribute.module.scss
  src/components/_pages/discoveries/detail/TriggerHistorySummaryViewer/triggerHistorySummaryViewer.module.scss
  src/components/_pages/locations/detail/locationDetail.module.scss
  src/components/_pages/roles/RolePermissionsEditor/style.module.scss
  src/components/_pages/rules/detail/rulesDetail.module.scss
  src/components/_pages/rules/list/conditions-list-component/conditionList.module.scss
  src/components/_pages/tokens/detail/RandomDataGeneration.tsx
  src/components/_pages/triggers/details/triggerDetails.module.scss
  src/ducks/alerts.ts
  src/ducks/auditLogs-epics.ts
  src/ducks/certificates-epics.ts
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/discoveries-epics.ts
  src/ducks/entities-epics.ts
  src/ducks/locations-epics.ts
  src/ducks/notifications-epics.ts
  src/ducks/scheduler-epics.ts
  src/index.tsx
  src/react-app-env.d.ts
  src/resources/styles/nunito.scss
  tsconfig.json
  vite.config.js
Labels: dependencies

#881 CRA to Vite transition deployment issue fix
  config.js
  default.conf
  index.html
  start-nginx.sh
  vite.config.js
Labels: bug, ignore-for-release

#880 CRA to Vite transition build fixes
  package-lock.json
  package.json
  src/components/ConditionAndExecutionItemsViewer/index.tsx
  src/components/ConditionFormFilter/index.tsx
  src/components/ExecutionConditionItemsList/index.tsx
  src/components/FilterWidget/index.tsx
  src/components/FilterWidgetRuleAction/index.tsx
  src/components/PagedList/PagedList.tsx
  src/components/_pages/actions/detail/index.tsx
  src/components/_pages/auditLogs/index.tsx
  src/components/_pages/certificates/list/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/components/_pages/discoveries/list/index.tsx
  src/components/_pages/entities/list/index.tsx
  src/components/_pages/locations/list/index.tsx
  src/components/_pages/rules/detail/index.tsx
  src/ducks/alerts.ts
  src/ducks/auditLogs-epics.ts
  src/ducks/certificates-epics.ts
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/discoveries-epics.ts
  src/ducks/entities-epics.ts
  src/ducks/filters.ts
  src/ducks/index.ts
  src/ducks/locations-epics.ts
  src/ducks/notifications-epics.ts
  src/ducks/scheduler-epics.ts
  src/ducks/transform/rules.tsx
  src/index.tsx
  src/resources/styles/app.scss
  src/resources/styles/theme.scss
  tsconfig.json
  vite.config.js
Labels: ignore-for-release
