Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2025-05, with the labels that each got.

#906 Add unit tests for AttributeEditor and CustomWidget testing
  .sonarcloud.properties
  cypress.d.ts
  cypress/component/Attributes/AttributeDescriptorViewer/AttributeDescriptorViewer.cy.tsx
  cypress/component/Attributes/AttributeEditor/AttributeEditor.cy.tsx
  cypress/component/Attributes/AttributeEditor/ConstraintChecks.cy.tsx
  cypress/component/Attributes/AttributeEditor/CustomAttributes.cy.tsx
  cypress/component/Attributes/AttributeEditor/DataAttributes.cy.tsx
  cypress/component/Attributes/AttributeEditor/FormInteractions.cy.tsx
  cypress/component/Attributes/AttributeEditor/GlobalModalAttributeEditor.cy.tsx
  cypress/component/Attributes/AttributeEditor/GroupCallbackAttributes.cy.tsx
  cypress/component/Attributes/AttributeEditor/InfoAttributes.cy.tsx
  cypress/component/Attributes/AttributeEditor/TabAttributeEditor.cy.tsx
  cypress/component/Attributes/AttributeEditor/mock-data.tsx
  cypress/component/Attributes/AttributeViewer/AttributeViewer.cy.tsx
  cypress/component/Attributes/CustomAttributeWidget/CustomAttributeWidget.cy.tsx
  cypress/component/Attributes/CustomAttributeWidget/mock-data.ts
  cypress/component/_pages/users/form/form.cy.tsx
  cypress/support/commands.tsx
  cypress/support/component.js
  cypress/support/reduxActionListenerMiddleware.ts
  cypress/utils/constants.ts
  cypress/utils/invocationInterceptor.ts
  cypress/utils/mockClipboard.ts
  cypress/utils/selectors.ts
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/Attributes/AttributeEditor/CustomAttributeAddSelect/index.tsx
  src/components/Attributes/AttributeEditor/index.tsx
  src/components/Attributes/AttributeViewer/index.tsx
  src/components/Attributes/CustomAttributeWidget/index.tsx
  src/components/Input/DynamicContent/ContentValueField/index.tsx
  src/components/Widget/index.tsx
  src/components/WidgetButtons/index.tsx
Labels: enhancement

#910 Fix previous attributes disappearing when multiple/nested callback attributes are requested
  cypress/component/Attributes/AttributeEditor/GroupCallbackAttributes.cy.tsx
  src/components/Attributes/AttributeEditor/index.tsx
Labels: bug

#914 Fix update token in Token profile edit form
  src/components/_pages/token-profiles/form/index.tsx
Labels: bug

#920 Fix internal notification profile badge color
  src/components/_pages/notifications/notification-profiles/detail/index.tsx
  src/components/_pages/notifications/notification-profiles/list/index.tsx
Labels: ignore-for-release
