Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2025-02, with the labels that each got.

#837 Create codeql.yml
  .github/workflows/codeql.yml
Labels: ignore-for-release

#820 Update state on connector reconnect to reflect changes in connector kinds and function groups
  src/ducks/connectors.ts
Labels: bug

#838 Fix editing of CRON expression of scheduled job
  src/components/_pages/scheduler/detail/index.tsx
Labels: bug

#839 Make permission widgets sticky in role permission editor
  src/components/Layout/Layout.module.scss
  src/components/_pages/roles/RolePermissionsEdior/index.tsx
  src/components/_pages/roles/RolePermissionsEdior/style.module.scss
  src/components/_pages/roles/RolePermissionsForm/index.tsx
Labels: enhancement

#819 Always show "Add New" button on credential attribute
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/types/user-interface.tsx
Labels: bug

#849 Add text wrapping to Badge elements
  src/components/FilterWidget/FilterWidget.module.scss
Labels: bug

#848 Update Role Permissions Editor UI
  src/components/Widget/index.tsx
  src/components/_pages/roles/RolePermissionsEdior/index.tsx
  src/components/_pages/roles/RolePermissionsEdior/style.module.scss
  src/components/_pages/roles/RolePermissionsForm/index.tsx
  src/components/_pages/roles/RolePermissionsForm/style.module.scss
  src/resources/styles/_global.scss
  src/resources/styles/theme.scss
Labels: enhancement

#855 Copy correct content of attribute in AttributeViewer based on attribute content type
  src/components/Attributes/AttributeViewer/attributeViewer.module.scss
  src/components/Attributes/AttributeViewer/index.tsx
  src/utils/attributes/attributes.tsx
Labels: bug

#856 Update the key detail and form pages to handle keys without token instance
  README.md
  src/components/AppRouter.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/cryptographic-keys/form/index.tsx
  src/components/_pages/cryptographic-keys/list/index.tsx
  src/ducks/cryptographic-keys-epics.ts
  src/ducks/cryptographic-keys.ts
  src/ducks/rules-epics.ts
  src/ducks/transform/auth.ts
  src/ducks/transform/cryptographic-keys.ts
  src/types/auth.ts
  src/types/cryptographic-keys.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/ApprovalInventoryApi.ts
  src/types/openapi/apis/ApprovalProfileInventoryApi.ts
  src/types/openapi/apis/CertificateInventoryApi.ts
  src/types/openapi/apis/CryptographicKeyControllerApi.ts
  src/types/openapi/apis/InternalNotificationApi.ts
  src/types/openapi/apis/ScheduledJobsManagementApi.ts
  src/types/openapi/models/ApprovalProfileDetailDto.ts
  src/types/openapi/models/ApprovalProfileDto.ts
  src/types/openapi/models/ApprovalProfileRequestDto.ts
  src/types/openapi/models/AuthActionDto.ts
  src/types/openapi/models/AuthResourceDto.ts
  src/types/openapi/models/DataAttribute.ts
  src/types/openapi/models/EditKeyRequestDto.ts
  src/types/openapi/models/index.ts
  src/types/openapi/servers.ts
  tsconfig.json
Labels: enhancement

#852 Use display name for action in RolePermissionsEditor
  cypress/component/Attributes/CustomAttributeWidget/mock-data.ts
  cypress/component/CertificateAttributes/mock-data.ts
  cypress/component/_pages/users/form/mock-data.ts
  src/components/_pages/roles/RolePermissionsEditor/index.tsx
  src/components/_pages/roles/RolePermissionsEditor/style.module.scss
  src/components/_pages/roles/RolePermissionsForm/index.tsx
Labels: bug

#821 Add custom attribute selector in Attribute Editor
  cypress/component/Attributes/AttributeEditor/AttributeEditor.cy.tsx
  cypress/component/Attributes/AttributeEditor/mock-data.tsx
  src/components/Attributes/AttributeEditor/CustomAttributeAddSelect/index.tsx
  src/components/Attributes/AttributeEditor/index.tsx
Labels: enhancement

#858 Fix Flow view in Certificate detail page missing groups and owner
  src/components/_pages/certificates/detail/index.tsx
  src/ducks/transform/certificates.tsx
  src/utils/download.ts
Labels: bug

#862 Fix the text overflow in the FlowChart Nodes entity labels
  src/components/FlowChart/CustomFlowNode/customFlowNode.module.scss
  src/components/FlowChart/flowChart.module.scss
  src/components/FlowChart/index.tsx
Labels: bug
