Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2025-04, with the labels that each got.

#890 Fix sending content of required boolean attribute in AttributeEditor
  src/components/Attributes/AttributeEditor/Attribute/index.tsx
  src/components/Attributes/AttributeEditor/index.tsx
  src/utils/validators.ts
Labels: bug

#894 Update API models and fix typing
  cypress/component/Attributes/AttributeEditor/AttributeEditor.cy.tsx
  cypress/component/CertificateAttributes/mock-data.ts
  src/components/_pages/acme-accounts/detail/index.tsx
  src/components/_pages/approval-profiles/form/index.tsx
  src/components/_pages/approvals/list/index.tsx
  src/components/_pages/authorities/detail/index.tsx
  src/components/_pages/authorities/form/index.tsx
  src/components/_pages/certificates/detail/index.tsx
  src/components/_pages/certificates/form/index.tsx
  src/components/_pages/credentials/detail/index.tsx
  src/components/_pages/credentials/form/index.tsx
  src/components/_pages/cryptographic-keys/detail/CryptographicKeyItem.tsx
  src/components/_pages/cryptographic-keys/detail/index.tsx
  src/components/_pages/entities/detail/index.tsx
  src/components/_pages/entities/form/index.tsx
  src/components/_pages/ra-profiles/CertificateValidationDialogBody.tsx
  src/components/_pages/ra-profiles/detail/index.tsx
  src/ducks/approval-profiles-epics.ts
  src/ducks/approvals-epic.ts
  src/ducks/approvals.ts
  src/ducks/notifications-epics.ts
  src/ducks/scheduler-epics.ts
  src/ducks/transform/scheduler.ts
  src/types/approvals.ts
  src/types/openapi/.openapi-generator/FILES
  src/types/openapi/apis/ApprovalInventoryApi.ts
  src/types/openapi/apis/ApprovalProfileInventoryApi.ts
  src/types/openapi/apis/CertificateInventoryApi.ts
  src/types/openapi/apis/InternalNotificationApi.ts
  src/types/openapi/apis/ScheduledJobsManagementApi.ts
  src/types/openapi/models/AcmeAccountListResponseDto.ts
  src/types/openapi/models/AcmeAccountResponseDto.ts
  src/types/openapi/models/ApprovalProfileDetailDto.ts
  src/types/openapi/models/ApprovalProfileDto.ts
  src/types/openapi/models/ApprovalStepRecipientDto.ts
  src/types/openapi/models/AuthorityInstanceDto.ts
  src/types/openapi/models/CertificateDetailDto.ts
  src/types/openapi/models/CertificateDto.ts
  src/types/openapi/models/CertificateRequestDto.ts
  src/types/openapi/models/CredentialDto.ts
  src/types/openapi/models/EntityInstanceDto.ts
  src/types/openapi/models/KeyDetailDto.ts
  src/types/openapi/models/KeyDto.ts
  src/types/openapi/models/KeyItemDetailDto.ts
  src/types/openapi/models/KeyItemDto.ts
  src/types/openapi/models/RaProfileDto.ts
  src/types/openapi/models/TokenInstanceDetailDto.ts
  src/types/openapi/models/TokenInstanceDto.ts
  src/types/openapi/models/index.ts
  src/types/scheduler.ts
  src/utils/certificate.tsx
Labels: ignore-for-release

#895 Add platform version info dialog link to footer
  src/api.ts
  src/components/Layout/Footer/index.tsx
  src/components/Layout/PlatformInfoDialogButton/index.tsx
  src/ducks/index.ts
  src/ducks/info-epics.ts
  src/ducks/info.ts
  src/ducks/reducers.ts
  src/types/info.ts
Labels: enhancement

#896 Add Protocol info widget to Certificate detail page
  src/components/_pages/certificates/detail/index.tsx
Labels: enhancement

#898 Add unit tests for validators
  cypress/component/utils/validators.cy.ts
  src/components/_pages/acme-profiles/form/index.tsx
  src/components/_pages/auth-settings/form/index.tsx
  src/components/_pages/connectors/form/index.tsx
  src/utils/validators.ts
Labels: enhancement

#900 Update actions for the main branch
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/cypress-component.yml
  .github/workflows/publish_docker_3key.yml
  .github/workflows/publish_docker_czertainly.yml
  .github/workflows/publish_harbor_3key.yml
  .github/workflows/test_docker_image.yaml
Labels: ignore-for-release

#903 Fix async return value
  cypress/e2e/upload_certificate.cy.ts
Labels: ignore-for-release
