Repository CZERTAINLY/CZERTAINLY-FE-Administrator, pull requests merged in 2025-06, with the labels that each got.

#936 Show correct recipient type badge in notification profile detail page
  src/components/_pages/notifications/notification-profiles/detail/index.tsx
Labels: bug, ignore-for-release, codex

#929 Reset state on ASN.1 structure dialog close to prevent automatic opening of dialog on other certificate page
  src/components/_pages/certificates/Asn1Dialog/Asn1Dialog.tsx
Labels: bug

#940 Fix redirects to certificate inventory from dashboard expiry statistics
  src/components/_pages/dashboard/index.tsx
  src/utils/dateUtil.tsx
Labels: bug

#941 Use correct resource for listing triggers for Certificate discovered event when adding new discovery
  src/components/_pages/discoveries/form/index.tsx
Labels: bug, ignore-for-release

#943 Update container build and vulnerability check
  .github/workflows/publish_docker_3key.yml
  .github/workflows/publish_docker_czertainly.yml
  .github/workflows/publish_harbor_3key.yml
  .github/workflows/test_docker_image.yaml
  config/trivy.yaml
Labels: enhancement

#942 Update release version to 2.15.0
  package.json
Labels: ignore-for-release

#944 Fix loading of pre-build container for trivy scan
  .github/workflows/publish_docker_3key.yml
  .github/workflows/publish_docker_czertainly.yml
  .github/workflows/publish_harbor_3key.yml
  .github/workflows/test_docker_image.yaml
Labels: ignore-for-release

#946 Fix pagination of notification profiles listing
  src/components/_pages/executions/SendNotificationExecutionItems/index.tsx
  src/components/_pages/notifications/notification-profiles/form/index.tsx
  src/components/_pages/notifications/notification-profiles/list/index.tsx
  src/ducks/filters.ts
  src/ducks/notification-profiles-epics.ts
  src/ducks/notification-profiles.ts
Labels: codex
